# -*- coding: utf-8 -*-
"""Kmean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VWiGEWoN8AbKpXcjz-PFD8HkWH81xeLr
"""

from sklearn.cluster import KMeans
import pandas as pd

data = pd.DataFrame({
    'salary': [90, 85, 20, 25],
    'spending': [88, 92, 30, 25]
})

model = KMeans(n_clusters=2)    #kvalue

model.fit(data) #no need to give x,y seperately thus why its called unsup

print(model.labels_) #denoting data belogs under which cluster