# -*- coding: utf-8 -*-
"""PCA with scaling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EoyyPc5NL51vpTOXIXTKXogkkSeFkZlw
"""

import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# ---------------------------------------------------
# CREATE DATASET
# ---------------------------------------------------
# Customer dataset

data = pd.DataFrame({
    'Age': [25, 45, 22, 35, 52],
    'Salary': [30000, 80000, 25000, 65000, 90000],
    'SpendingScore': [60, 30, 80, 40, 20]
})

print("Original Dataset:\n")
print(data)

# ---------------------------------------------------
# WHY SCALING?
# ---------------------------------------------------
# Age values:
# 22, 25, 35
#
# Salary values:
# 25000, 80000, 90000
#
# Salary numbers are much larger.
#
# PCA depends on variance/spread.
# So without scaling:
# Salary dominates PCA.
#
# To avoid this:
# We scale data into similar range.


# ---------------------------------------------------
# SCALING
# ---------------------------------------------------

# StandardScaler:
# Converts all columns into similar scale
#
# Formula:
#
# z = (x - mean) / standard deviation
#
# x   = original value
# mean = average of column
# std  = standard deviation

scaler = StandardScaler()

# fit():
# Learns mean & std from dataset
#
# transform():
# Applies scaling formula
#
# fit_transform():
# Both together

scaled_data = scaler.fit_transform(data)

print("\nScaled Data:\n")
print(scaled_data)

# Example scaled output:
#
# [[-0.83 -0.98  0.62]
#  [ 0.67  0.80 -0.66]
#  [-1.05 -1.15  1.47]
#  [ 0.00  0.27 -0.23]
#  [ 1.21  1.06 -1.19]]
#
# Understanding:
#
# Negative value -> below average
# Positive value -> above average
#
# Example:
# Salary 90000 becomes positive
# because it is above average salary


# ---------------------------------------------------
# PCA
# ---------------------------------------------------

# PCA = Principal Component Analysis
#
# Goal:
# Reduce number of columns
# while keeping important information
#
# Original columns:
# Age
# Salary
# SpendingScore
#
# PCA converts into:
# PC1
# PC2
#
# PC = Principal Component

pca = PCA(n_components=2)

# n_components=2 means:
#
# "Reduce dataset into 2 important features"

# fit():
# PCA studies data spread/variance
#
# transform():
# Converts original data into compressed features

pca_data = pca.fit_transform(scaled_data)

print("\nPCA Reduced Data:\n")
print(pca_data)

# Example output:
#
# [[-1.58  0.12]
#  [ 1.20 -0.30]
#  [-2.01  0.42]
#  [ 0.45 -0.11]
#  [ 1.94 -0.13]]
#
# Understanding:
#
# Before PCA:
# Age | Salary | SpendingScore
#
# After PCA:
# PC1 | PC2
#
# 3 columns reduced into 2 columns


# ---------------------------------------------------
# EXPLAINED VARIANCE RATIO
# ---------------------------------------------------

# explained_variance_ratio_
#
# Shows how much information
# each principal component preserves

print("\nExplained Variance Ratio:\n")
print(pca.explained_variance_ratio_)

# Example output:
#
# [0.91 0.07]
#
# Meaning:
#
# PC1 keeps 91% information
# PC2 keeps 7% information
#
# Total:
# 98% information preserved


# ---------------------------------------------------
# FINAL FLOW
# ---------------------------------------------------

# Original Data
# ↓
# Scaling
# ↓
# PCA
# ↓
# Reduced Important Data
#
# Like:
# 100-page summary of 1000-page book