# -*- coding: utf-8 -*-
"""Decision Tree Classifiers .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gLM3gH89Nn3z8X4KEqER4Am_W837to8E
"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

# dataset
data = {
    "age": [22,25,47,52,46,56],
    "salary": [15000,20000,50000,60000,52000,65000],
    "buy": [0,0,1,1,1,1]
}

df = pd.DataFrame(data)

X = df[["age","salary"]]
y = df["buy"]

# split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# model
model = DecisionTreeClassifier(
    criterion="gini",
    max_depth=3
)

# train
model.fit(X_train, y_train)

# predict
pred = model.predict(X_test)

print(pred)

# accuracy
print(accuracy_score(y_test, pred))

import kagglehub
import pandas as pd
import os

from sklearn.ensemble import RandomForestRegressor # Changed from DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Download dataset
path = kagglehub.dataset_download(
    "nalisha/car-price-prediction-dataset"
)

print("Dataset downloaded at:", path)

# Find CSV file automatically
csv_path = None

for root, dirs, files in os.walk(path):
    for file in files:
        if file.endswith(".csv"):
            csv_path = os.path.join(root, file)
            print("CSV Found:", csv_path)

# Read dataset
data = pd.read_csv(csv_path)

data=data.dropna()

# Features and target
# Drop 'Car ID' as it is an identifier and not a predictive feature
X = data.drop(columns=["Price", "Car ID"])
y = data["Price"]

# Convert categorical columns to numerical
X = pd.get_dummies(X)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Create model using RandomForestRegressor
model = RandomForestRegressor(
    random_state=42, # For reproducibility
    n_estimators=100, # Number of trees in the forest (default is 100)
    max_depth=10 # Keep max_depth for now
)

# Train model
model.fit(X_train, y_train)

# Prediction
pred = model.predict(X_test)

# Evaluate model
mse = mean_squared_error(y_test, pred)
r2 = r2_score(y_test, pred)

print("MSE:", mse)
print("R-squared:", r2)

"""### Analyzing Categorical Features

High cardinality (many unique values) in categorical features can lead to a very large number of columns after one-hot encoding, which can sometimes hinder model performance. Let's examine the unique values in the categorical columns to identify any potential issues.
"""

# Identify categorical columns (object type) before one-hot encoding
categorical_cols = data.select_dtypes(include='object').columns

print("Unique value counts for categorical columns:")
for col in categorical_cols:
    print(f"- {col}: {data[col].nunique()} unique values")
    if data[col].nunique() > 50: # Arbitrary threshold to flag potentially problematic columns
        print(f"  (Potential high cardinality detected for {col})")