# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZwM64ICUY_iRPrbfO96NcFVEsMm03uaA
"""

from sklearn.neighbors import KNeighborsClassifier

# Features
X = [
    [1, 20],
    [2, 30],
    [3, 40],
    [6, 70],
    [7, 80],
    [8, 90]
]

# Labels
y = [0, 0, 0, 1, 1, 1]

# Create model
model = KNeighborsClassifier(n_neighbors=3)

# Train
model.fit(X, y)

# New employee
new_data = [[5, 60]]

# Prediction
prediction = model.predict(new_data)

print(prediction)