# -*- coding: utf-8 -*-
"""Linearregression using sklearn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iUw0NmUeNqFTUXJr_ezi61bN4CzgVpXW
"""

#LinearRegression used for prectict continuous numerical values
import pandas as pd
from sklearn.linear_model import LinearRegression

data={
    "Hours":[1,3,5,7,8],
    "Marks"  :[17,37,57,77,88]
}

df=pd.DataFrame(data)

x=df[["Hours"]]   # enter the columns name for training
y=df[["Marks"]]   #output column, here mark is our prediction

model=LinearRegression()

model.fit(x,y)

io=int(input("Enter the hours:"))
new_data=pd.DataFrame({"Hours":[io]})
print(model.predict(new_data))

#Or

#print(model.predict([[9]]))



