# -*- coding: utf-8 -*-
"""Logistic regression using sklearn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAm-XRVdytesH1ebDAXs8EX65jyW0xJ-
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression

data = {
    "Hours": [1,2,3,5,7],
    "Placed": [0,0,0,1,1]
}

df = pd.DataFrame(data)

X = df[["Hours"]]
y = df["Placed"]

model = LogisticRegression()

model.fit(X, y)

pred = model.predict([[6]])

print(pred)