# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FTozsPX9J2sm4lVRpSlemndOuniGIVsh
"""

from sklearn.svm import SVC
import numpy as np

# -----------------------------
# STEP 1 : Features (X)
# -----------------------------
# [Experience, Skill Score]

X = np.array([
    [1, 20],
    [2, 30],
    [3, 40],
    [6, 70],
    [7, 80],
    [8, 90]
])

# -----------------------------
# STEP 2 : Target (y)
# -----------------------------
# 0 = Rejected
# 1 = Selected

y = np.array([0, 0, 0, 1, 1, 1])

# -----------------------------
# STEP 3 : Create SVM Model
# -----------------------------

model = SVC(kernel='linear')

# -----------------------------
# STEP 4 : Train Model
# -----------------------------

model.fit(X, y)

# -----------------------------
# STEP 5 : New Employee
# -----------------------------

new_employee = [[5, 60]]

# -----------------------------
# STEP 6 : Prediction
# -----------------------------

prediction = model.predict(new_employee)

print("Prediction:", prediction)